export const blogPosts = [
  {
    id: "madinah-to-badar-badr-ziyarat-return-taxi-fare-service",
    title: "Madinah to Badar & Badr Ziyarat & Return Taxi Fare & Service",
    excerpt: "The trip from Madinah to Badar is one of the most demanded ziyarat visits by pilgrims. Book your Madinah to Badar and Badr ziyarat with a round-trip taxi that is easy, secure, and customer-oriented.",
    categories: ["taxi-fares"],
    date: "2026-04-08",
    readTime: "6 min read",
    image: "/images/Madinah-to-Badar-Badr-Ziyarat-Return-Taxi-Fare-Service.jpg",
    author: "M Umar Irfan",
  },
  {
    id: "hajj-quota-by-country-hajj-cost-waiting-list-by-country",
    title: "Hajj Quota by Country, Hajj Cost & Waiting List by Country",
    excerpt: "Complete guide to Hajj quota by country for 2026, real costs from over 10 countries, government subsidies, and waiting list information for pilgrims worldwide.",
    categories: ["other-services"],
    date: "2026-04-08",
    readTime: "12 min read",
    image: "/images/hajj-quota-by-country-hajj-cost-waiting-list-by-country.jpg",
    author: "M Umar Irfan",
  },
  {
    id: "cheap-wadi-e-jinn-ziyarat-taxi-madinah-to-wadi-e-jinn-taxi",
    title: "Cheap Wadi e Jinn Ziyarat Taxi | Madinah to Wadi e Jinn Taxi",
    excerpt: "Discover affordable Wadi e Jinn ziyarat taxi service from Madinah. Book your comfortable ride to this popular desert destination with Haramain Umrah Taxi.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-03-27",
    readTime: "5 min read",
    image: "/images/cheap-wadi-e-jinn-ziyarat-taxi-madinah-to-wadi-e-jinn-taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-places-to-visit-in-dammam-things-to-do-in-dammam-ksa",
    title: "Best Places to Visit in Dammam & Things to Do in Dammam, KSA",
    excerpt: "Discover the best places to visit in Dammam, KSA. From Half Moon Beach to shopping malls, explore top attractions and things to do in this vibrant Eastern Province city.",
    categories: ["other-services"],
    date: "2026-04-25",
    readTime: "8 min read",
    image: "/images/best-places-to-visit-in-dammam-things-to-do-in-dammam-ksa.png",
    author: "M Umar Irfan",
  },
  {
    id: "ziyarat-and-umrah-taxi-services-in-shawal-ksa",
    title: "Ziarat and Umrah Taxi Services in Shawal - Discounts Available",
    excerpt: "Discover discounted Umrah taxi services in Shawal. Reliable transport for Makkah to Madinah, airport transfers, and Ziarat tours with professional drivers.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-25",
    readTime: "7 min read",
    image: "/images/ziyarat-and-umrah-taxi-services-in-shawal-ksa.png",
    author: "M Umar Irfan",
  },
  {
    id: "eid-ul-fitr-taxi-services-in-makkah-madinah-saudi-arabia",
    title: "Eid ul Fitr Taxi Services in Makkah & Madinah, Saudi Arabia",
    excerpt: "Reliable Eid ul Fitr taxi services in Makkah and Madinah. Book online for airport transfers, intercity travel, and Ziarat tours during the busy Eid season.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-25",
    readTime: "6 min read",
    image: "/images/eid-ul-fitr-taxi-services-in-makkah-madinah-saudi-arabia.png",
    author: "M Umar Irfan",
  },
  {
    id: "private-umrah-taxi-services-from-indonesia",
    title: "Book Private Umrah Taxi Services Online from Indonesia",
    excerpt: "Book private Umrah taxi services online from Indonesia. Reliable transport for Indonesian pilgrims with comfortable vehicles and professional drivers.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-25",
    readTime: "6 min read",
    image: "/images/private-umrah-taxi-services-from-indonesia.png",
    author: "M Umar Irfan",
  },
];
