export const blogPosts = [
  {
    id: "madinah-to-badar-badr-ziyarat-return-taxi-fare-service",
    title: "Madinah to Badar & Badr Ziyarat & Return Taxi Fare & Service",
    excerpt: "The trip from Madinah to Badar is one of the most demanded ziyarat visits by pilgrims. Book your Madinah to Badar and Badr ziyarat with a round-trip taxi that is easy, secure, and customer-oriented.",
    categories: ["taxi-fares"],
    date: "2026-04-08",
    readTime: "6 min read",
    image: "/images/Madinah-to-Badar-Badr-Ziyarat-Return-Taxi-Fare-Service.jpg",
    author: "M Umar Irfan",
  },
  {
    id: "hajj-quota-by-country-hajj-cost-waiting-list-by-country",
    title: "Hajj Quota by Country, Hajj Cost & Waiting List by Country",
    excerpt: "Complete guide to Hajj quota by country for 2026, real costs from over 10 countries, government subsidies, and waiting list information for pilgrims worldwide.",
    categories: ["other-services"],
    date: "2026-04-08",
    readTime: "12 min read",
    image: "/images/hajj-quota-by-country-hajj-cost-waiting-list-by-country.jpg",
    author: "M Umar Irfan",
  },
  {
    id: "cheap-wadi-e-jinn-ziyarat-taxi-madinah-to-wadi-e-jinn-taxi",
    title: "Cheap Wadi e Jinn Ziyarat Taxi | Madinah to Wadi e Jinn Taxi",
    excerpt: "Discover affordable Wadi e Jinn ziyarat taxi service from Madinah. Book your comfortable ride to this popular desert destination with Haramain Umrah Taxi.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-03-27",
    readTime: "5 min read",
    image: "/images/cheap-wadi-e-jinn-ziyarat-taxi-madinah-to-wadi-e-jinn-taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-places-to-visit-in-dammam-things-to-do-in-dammam-ksa",
    title: "Best Places to Visit in Dammam & Things to Do in Dammam, KSA",
    excerpt: "Discover the best places to visit in Dammam, KSA. From Half Moon Beach to shopping malls, explore top attractions and things to do in this vibrant Eastern Province city.",
    categories: ["other-services"],
    date: "2026-04-25",
    readTime: "8 min read",
    image: "/images/best-places-to-visit-in-dammam-things-to-do-in-dammam-ksa.png",
    author: "M Umar Irfan",
  },
  {
    id: "ziyarat-and-umrah-taxi-services-in-shawal-ksa",
    title: "Ziarat and Umrah Taxi Services in Shawal - Discounts Available",
    excerpt: "Discover discounted Umrah taxi services in Shawal. Reliable transport for Makkah to Madinah, airport transfers, and Ziarat tours with professional drivers.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-25",
    readTime: "7 min read",
    image: "/images/ziyarat-and-umrah-taxi-services-in-shawal-ksa.png",
    author: "M Umar Irfan",
  },
  {
    id: "eid-ul-fitr-taxi-services-in-makkah-madinah-saudi-arabia",
    title: "Eid ul Fitr Taxi Services in Makkah & Madinah, Saudi Arabia",
    excerpt: "Reliable Eid ul Fitr taxi services in Makkah and Madinah. Book online for airport transfers, intercity travel, and Ziarat tours during the busy Eid season.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-25",
    readTime: "6 min read",
    image: "/images/eid-ul-fitr-taxi-services-in-makkah-madinah-saudi-arabia.png",
    author: "M Umar Irfan",
  },
  {
    id: "private-umrah-taxi-services-from-indonesia",
    title: "Book Private Umrah Taxi Services Online from Indonesia",
    excerpt: "Book private Umrah taxi services online from Indonesia. Reliable transport for Indonesian pilgrims with comfortable vehicles and professional drivers.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-25",
    readTime: "6 min read",
    image: "/images/private-umrah-taxi-services-from-indonesia.png",
    author: "M Umar Irfan",
  },
  {
    id: "7-best-tourist-places-to-visit-in-tabuk-things-to-do-in-tabuk",
    title: "7 Best Tourist Places to Visit in Tabuk & Things to Do in Tabuk",
    excerpt: "Discover the best places to visit in Tabuk, KSA. From Tabuk Castle to Wadi Al Disah, explore top attractions and things to do in this fascinating northwestern Saudi city.",
    categories: ["other-services"],
    date: "2026-04-27",
    readTime: "10 min read",
    image: "/images/7-best-tourist-places-to-visit-in-tabuk-things-to-do-in-tabuk.png",
    author: "M Umar Irfan",
  },
  {
    id: "private-umrah-taxi-services-online-from-the-usa-book-at-discount",
    title: "Private Umrah Taxi Services Online from the USA Book at Discount",
    excerpt: "Book private Umrah taxi services online from the USA at discount. Reliable airport transfers, Makkah to Madinah travel, and comfortable transportation for USA pilgrims.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-04-27",
    readTime: "8 min read",
    image: "/images/private-umrah-taxi-services-online-from-the-usa-book-at-discount.png",
    author: "M Umar Irfan",
  },
  {
    id: "difference-betweeen-damm-fidyah-kaffarah",
    title: "Difference Between Damm, Fidyah, and Kaffarah in Easy Words",
    excerpt: "Understand the difference between Damm, Fidyah, and Kaffarah in Islam. Learn when each applies, the type of compensation required, and examples for Umrah, Hajj, and Ramadan.",
    categories: ["other-services"],
    date: "2026-04-27",
    readTime: "7 min read",
    image: "/images/difference-betweeen-damm-fidyah-kaffarah.png",
    author: "M Umar Irfan",
  },
  {
    id: "book-private-haramain-umrah-taxi-online-for-uk-pilgrims",
    title: "Book Private Haramain Umrah Taxi Online for UK Pilgrims",
    excerpt: "Book your private umrah taxi online before you travel from the UK. Enjoy a smooth airport transfer to Makkah or Madinah without stress. Book with Discounts!",
    categories: ["other-services", "taxi-fares"],
    date: "2026-05-11",
    readTime: "8 min read",
    image: "/images/book-private-haramain-umrah-taxi-online-for-uk-pilgrims.png",
    author: "M Umar Irfan",
  },
  {
    id: "nusuk-masar-how-to-apply-umrah-visa-through-nusuk-in-2026",
    title: "Nusuk Masar: How to Apply Umrah Visa through Nusuk in 2026",
    excerpt: "Learn how to apply for Umrah visa through Nusuk Masar in 2026, including process, fees, requirements & transport booking tips. Apply Umrah Visa & Book Our Taxi",
    categories: ["other-services"],
    date: "2026-05-11",
    readTime: "9 min read",
    image: "/images/nusuk-masar-how-to-apply-umrah-visa-through-nusuk.png",
    author: "M Umar Irfan",
  },
  {
    id: "uber-vs-taxi-why-is-a-haramain-umrah-taxi-cheaper-than-uber",
    title: "Uber vs Taxi: Why is a Haramain Umrah Taxi Cheaper than Uber",
    excerpt: "Compare Uber vs Taxi for Umrah travel and discover why Haramain Umrah Taxi is cheaper than Uber. Enjoy fixed pricing, no surge fares, and reliable transfers.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-05-11",
    readTime: "7 min read",
    image: "/images/Uber-vs-Taxi-Why-is-a-Haramain-Umrah-Taxi-Cheaper-than-Uber.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-umrah-taxi-service-in-ramadan-haramain-umrah-taxi-book",
    title: "Best Umrah Taxi Service in Ramadan: Haramain Umrah Taxi Book",
    excerpt: "Haramain Umrah Taxi offers the best Ramadan taxi service in Makkah & Madinah. Affordable, reliable, Clean Vehicles & 24/7 available. Book your Ride Now.",
    categories: ["other-services", "taxi-fares"],
    date: "2026-05-11",
    readTime: "10 min read",
    image: "/images/Best-Umrah-Taxi-Service-in-Ramadan-Haramain-Umrah-Taxi-Book.png",
    author: "M Umar Irfan",
  },
  {
    id: "safe-best-taxi-pickup-points-spots-near-masjid-al-haram",
    title: "Safe & Best Taxi Pickup Points & Spots near Masjid Al Haram",
    excerpt: "Best pickup points near Haram for pilgrims. Read about safe, convenient locations at all gates. Book your Haramain Umrah Taxi ride now at Discounted Price!",
    categories: ["other-services", "taxi-fares"],
    date: "2026-05-11",
    readTime: "8 min read",
    image: "/images/Safe-Best-Taxi-Pickup-Points-Spots-near-Masjid-Al-Haram-Haramain-Umrah-Taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-book-the-best-umrah-taxi-online-in-makkah-from-the-uk",
    title: "How to Book The Best Umrah Taxi Online in Makkah from the UK?",
    excerpt: "Book your Umrah taxi from the UK to Madinah with ease. Enjoy reliable service, comfortable vehicles, transparent pricing, and smooth transfers with Us!",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "9 min read",
    image: "/images/How-to-Book-The-Best-Umrah-Taxi-Online-in-Makkah-from-the-UK.png",
    author: "M Umar Irfan",
  },
  {
    id: "are-taxi-services-available-at-train-stations-in-saudi-arabia",
    title: "Are Taxi Services Available at Train Stations in Saudi Arabia?",
    excerpt: "Find out if taxis are available at Saudi train stations. Discover easy booking options for Makkah and Madinah hotel transfers with trusted Umrah taxi service.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "8 min read",
    image: "/images/Are-Taxi-Services-Available-at-Train-Stations-in-Saudi-Arabia.png",
    author: "M Umar Irfan",
  },
  {
    id: "jeddah-airport-parking-fees-hajj-north-terminal-1",
    title: "Jeddah Airport Parking Fees: Hajj, North & Terminal 1",
    excerpt: "Complete guide by Haramain Umrah Taxi to Jeddah Airport parking charges at Terminal 1, Hajj & North terminals. Long-term & VIP options. Plan your budget now.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Jeddah-Airport-Parking-Charges-Hajj-North-Terminal-1.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-perform-hajj-badal-for-a-deceased-dead-person",
    title: "How to Perform Hajj Badal for a Deceased & Dead Person?",
    excerpt: "Learn how to perform Hajj Badal for deceased loved ones. Complete step-by-step guide by Haramain Umrah Taxi with rituals & requirements. Book Now.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/How-to-Perform-Hajj-Badal-for-a-Deceased-Dead-Person-.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-perform-umrah-badal-for-a-deceased-dead-person",
    title: "How to Perform Umrah Badal for a Deceased & Dead Person?",
    excerpt: "Discover how to perform Umrah Badal for a deceased person with proper intention and rituals. Trust Haramain Umrah Taxi for reliable Umrah Badal services.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "10 min read",
    image: "/images/How-to-Perform-Umrah-Badal-for-a-Deceased-Dead-Person.png",
    author: "M Umar Irfan",
  },
  {
    id: "wadi-hanifa-garden-park-riyadh-a-complete-tour-guide",
    title: "Wadi Hanifa Garden & Park, Riyadh: A Complete Tour Guide",
    excerpt: "Explore Wadi Hanifa Garden & Park in Riyadh with our complete tour guide with attractions, tips, and travel help by Haramain Umrah Taxi.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Wadi-Hanifa-Garden-Park-Riyadh-A-Complete-Tour-Guide.png",
    author: "M Umar Irfan",
  },
  {
    id: "14-important-taxi-tips-for-pilgrims-or-travelers-in-ksa",
    title: "14 Important Taxi Tips for Pilgrims or Travelers in KSA",
    excerpt: "Learn 14 taxi tips for pilgrims or travelers in KSA. Trust Haramain Umrah Taxi, we follow every safety guideline to protect our pilgrims and tourists.",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/14-Important-Taxi-Tips-for-Pilgrims-or-Travelers-in-KSA.png",
    author: "M Umar Irfan",
  },
  {
    id: "taxi-fare-from-makkah-to-taif-taif-to-makkah-taif-ziyarat",
    title: "Taxi Fare from Makkah to Taif & Taif to Makkah &Taif Ziyarat",
    excerpt: "Affordable taxi service from Makkah to Taif. Rates from SAR 380. Ziyarat tours included. Book Camry, GMC, Hiace, Coaster & Bus. Available 24/7.",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Taxi-Fare-from-Makkah-to-Taif-Taif-to-Makkah-Taif-Ziyarat.png",
    author: "M Umar Irfan",
  },
  {
    id: "taxi-fare-from-makkah-to-masjid-ayesha-masjid-jarana-mikat",
    title: "Taxi Fare from Makkah to Masjid Ayesha & Masjid Jarana Mikat",
    excerpt: "Get reasonable taxi fares from Makkah to Masjid Ayesha & Masjid Jarana Miqat. Fixed rates, 24/7 service. Book your Umrah transport with Haramain Umrah Taxi.",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Taxi-Fare-from-Makkah-to-Masjid-Ayesha-Masjid-Jarana-Mikat.png",
    author: "M Umar Irfan",
  },
  {
    id: "is-it-safe-to-use-taxi-service-in-makkah-medina-ksa-at-night",
    title: "Is it Safe to Use Taxi Service in Makkah, Medina, KSA at Night?",
    excerpt: "People ask, is it safe to use taxi service in Makkah, Medina, KSA at night? Haramain Umrah Taxi offers secure 24/7 travel with verified drivers & GPS tracking.",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Is-it-Safe-to-Use-Taxi-Service-in-Makkah-Medina-KSA-at-Night.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-women-or-female-friendly-taxi-services-in-saudi-arab",
    title: "Best Women or Female-Friendly Taxi Services in Saudi Arab",
    excerpt: "Traveling as a woman in Saudi Arabia just got safer and more comfortable. Discover the best women or female-friendly taxi services in Saudi Arab. Book HUT!",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/Best-Women-or-Female-Friendly-Taxi-Services-in-Saudi-Arab.png",
    author: "M Umar Irfan",
  },
  {
    id: "makkah-train-station-to-hotel-masjid-al-haram-taxi-fare",
    title: "Makkah Train Station to Hotel & Masjid Al Haram Taxi Fare",
    excerpt: "Find the affordable Makkah Train Station to Hotel & Masjid Al Haram Taxi Fare at HUT. We offer comfortable transfers for pilgrims. Reserve your ride with Us!",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Makkah-Train-Station-to-Hotel-Masjid-Al-Haram-Taxi-Fare-1.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-book-a-taxi-in-saudi-arabia-for-international-visitors",
    title: "How to Book a Taxi in Saudi Arabia for International Visitors?",
    excerpt: "Learn how to book taxi in Saudi Arabia for international visitors. You can travel comfortably between holy cities and do ziyarats. Book HUT today!",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/How-to-Book-a-Taxi-in-Saudi-Arabia-for-International-Visitors.png",
    author: "M Umar Irfan",
  },
];

export const POSTS_PER_PAGE = 9;

export const sortedBlogPosts = [...blogPosts].sort(
  (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
);
