export const blogPosts = [
  {
    id: "best-umrah-taxi-service-in-rabiulawal",
    title: "Best Umrah Taxi Service in Rabi-ul-Awal in Makkah & Madinah",
    excerpt: "Haramain Umrah Taxi offers the best Umrah taxi service in Rabi-ul-Awal in Makkah & Madinah. Book airport transfers, intercity routes & Ziyarat rides. Reserve Now!",
    categories: ["taxi-guides"],
    date: "2026-07-09",
    readTime: "9 min read",
    image: "/images/Best Umrah Taxi Service in Rabi-ul-Awal in Makkah & Madinah.png",
    author: "M Umar Irfan",
  },
  {
    id: "madinah-to-badar-badr-ziyarat-return-taxi-fare-service",
    title: "Madinah to Badar & Badr Ziyarat & Return Taxi Fare & Service",
    excerpt: "Get a 7-seater private Starex or Staria Umrah taxi from Umrah Passenger at very discounted prices. Get Staria for Ziyarat, Airport and Inter-city transfers!",
    categories: ["sight-seeings"],
    date: "2026-04-08",
    readTime: "6 min read",
    image: "/images/Madinah-to-Badar-Badr-Ziyarat-Return-Taxi-Fare-Service.jpg",
    author: "M Umar Irfan",
  },
  {
    id: "hajj-quota-by-country-hajj-cost-waiting-list-by-country",
    title: "Hajj Quota by Country, Hajj Cost & Waiting List by Country",
    excerpt: "Hajj is a journey that a Muslim can make during his or her lifetime. It is one of the most significant ones. However, there is one thing that you need to know",
    categories: ["other-services"],
    date: "2026-04-08",
    readTime: "12 min read",
    image: "/images/hajj-quota-by-country-hajj-cost-waiting-list-by-country.jpg",
    author: "M Umar Irfan",
  },
  {
    id: "cheap-wadi-e-jinn-ziyarat-taxi-madinah-to-wadi-e-jinn-taxi",
    title: "Get Discounts for Wadi e Jinn Ziyarat Taxi from HUT. Travel 30-40km distance between Masjid Nabawi or Madinah to Wadi e Jinn in our Madinah to Wadi Jinn Taxi",
    excerpt: "Hajj is a journey that a Muslim can make during his or her lifetime. It is one of the most significant ones. However, there is one thing that you need to know",
    categories: ["sight-seeings"],
    date: "2026-03-27",
    readTime: "5 min read",
    image: "/images/cheap-wadi-e-jinn-ziyarat-taxi-madinah-to-wadi-e-jinn-taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-places-to-visit-in-dammam-things-to-do-in-dammam-ksa",
    title: "Best Places to Visit in Dammam & Things to Do in Dammam, KSA",
    excerpt: "Explore top tourist spots and the best places to visit in Dammam, KSA. Plan your trip and book a comfortable ride with Haramain Umrah Taxi.",
    categories: ["sight-seeings"],
    date: "2026-04-25",
    readTime: "8 min read",
    image: "/images/best-places-to-visit-in-dammam-things-to-do-in-dammam-ksa.png",
    author: "M Umar Irfan",
  },
  {
    id: "ziyarat-and-umrah-taxi-services-in-shawal-ksa",
    title: "Ziarat and Umrah Taxi Services in Shawal - Discounts Available",
    excerpt: "Haramain Umrah Taxi offers the best Umrah taxi services in Shawal with Discounts available! You can book Ziyarat taxi, Airport Transfers & Inter-city travel",
    categories: ["other-services"],
    date: "2026-04-25",
    readTime: "7 min read",
    image: "/images/ziyarat-and-umrah-taxi-services-in-shawal-ksa.png",
    author: "M Umar Irfan",
  },
  {
    id: "eid-ul-fitr-taxi-services-in-makkah-madinah-saudi-arabia",
    title: "Eid ul Fitr Taxi Services in Makkah & Madinah, Saudi Arabia",
    excerpt: "Want Eid Discount? Book Haramain's Eid ul Fitr Umrah Taxi with exclusive Eid offers! 24/7 Availability, Professional Drivers, Clean Cars for all Transfers!",
    categories: ["other-services"],
    date: "2026-04-25",
    readTime: "6 min read",
    image: "/images/eid-ul-fitr-taxi-services-in-makkah-madinah-saudi-arabia.png",
    author: "M Umar Irfan",
  },
  {
    id: "private-umrah-taxi-services-from-indonesia",
    title: "Book Private Umrah Taxi Services Online from Indonesia",
    excerpt: "You can book the best Ziyarat and Umrah taxi services from Indonesia in advance from Fater. Book Jeddah and Madinah Airport Pickups & Inter-city transfers.",
    categories: ["other-services"],
    date: "2026-04-25",
    readTime: "6 min read",
    image: "/images/private-umrah-taxi-services-from-indonesia.png",
    author: "M Umar Irfan",
  },
  {
    id: "7-best-tourist-places-to-visit-in-tabuk-things-to-do-in-tabuk",
    title: "Best Tourist Places to Visit in Tabuk &Things to Do in Tabuk",
    excerpt: "Book us to see top secret tourist places to visit in Tabuk i-e Tabuk Castle, Al Tawba Mosque, Wadi Al Disah, Jabal Al Lawz, Umluj Beach, Tabuk Malls & Parks",
    categories: ["sight-seeings"],
    date: "2026-04-27",
    readTime: "10 min read",
    image: "/images/7-best-tourist-places-to-visit-in-tabuk-things-to-do-in-tabuk.png",
    author: "M Umar Irfan",
  },
  {
    id: "private-umrah-taxi-services-online-from-the-usa-book-at-discount",
    title: "Private Umrah Taxi Services Online from USA Book at Discount",
    excerpt: "Book private Umrah taxi or car online from USA from Us at Discounted price. Get private car from Jeddah airport to Makkah & Madinah hotel to airport from USA",
    categories: ["other-services"],
    date: "2026-04-27",
    readTime: "8 min read",
    image: "/images/private-umrah-taxi-services-online-from-the-usa-book-at-discount.png",
    author: "M Umar Irfan",
  },
  {
    id: "difference-betweeen-damm-fidyah-kaffarah",
    title: "Difference Between Damm, Fidyah, and Kaffarah in Easy Words",
    excerpt: "Understand the difference between Damm, Fidyah, and Kaffarah in simple words. Learn when each applies during Hajj, Umrah, and Ramadan by Haramain Umrah Taxi",
    categories: ["other-services"],
    date: "2026-04-27",
    readTime: "7 min read",
    image: "/images/difference-betweeen-damm-fidyah-kaffarah.png",
    author: "M Umar Irfan",
  },
  {
    id: "book-private-haramain-umrah-taxi-online-for-uk-pilgrims",
    title: "Book Private Haramain Umrah Taxi Online for UK Pilgrims",
    excerpt: "Book your private umrah taxi online before you travel from the UK. Enjoy a smooth airport transfer to Makkah or Madinah without stress. Book with Discounts!",
    categories: ["other-services"],
    date: "2026-05-11",
    readTime: "8 min read",
    image: "/images/book-private-haramain-umrah-taxi-online-for-uk-pilgrims.png",
    author: "M Umar Irfan",
  },
  {
    id: "nusuk-masar-how-to-apply-umrah-visa-through-nusuk-in-2026",
    title: "Nusuk Masar: How to Apply Umrah Visa through Nusuk in 2026",
    excerpt: "Learn how to apply for Umrah visa through Nusuk Masar in 2026, including process, fees, requirements & transport booking tips. Apply Umrah Visa & Book Our Taxi",
    categories: ["other-services"],
    date: "2026-05-11",
    readTime: "9 min read",
    image: "/images/nusuk-masar-how-to-apply-umrah-visa-through-nusuk.png",
    author: "M Umar Irfan",
  },
  {
    id: "uber-vs-taxi-why-haramain-umrah-taxi-cheaper",
    title: "Uber vs Taxi: Why is a Haramain Umrah Taxi Cheaper than Uber",
    excerpt: "Compare Uber vs Taxi for Umrah travel and discover why Haramain Umrah Taxi is cheaper than Uber. Enjoy fixed pricing, no surge fares, and reliable transfers.",
    categories: ["other-services"],
    date: "2026-05-11",
    readTime: "7 min read",
    image: "/images/Uber-vs-Taxi-Why-is-a-Haramain-Umrah-Taxi-Cheaper-than-Uber.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-umrah-taxi-service-in-ramadan",
    title: "Best Umrah Taxi Service in Ramadan: Haramain Umrah Taxi Book",
    excerpt: "Haramain Umrah Taxi offers the best Ramadan taxi service in Makkah & Madinah. Affordable, reliable, Clean Vehicles & 24/7 available. Book your Ride Now.",
    categories: ["other-services"],
    date: "2026-05-11",
    readTime: "10 min read",
    image: "/images/Best-Umrah-Taxi-Service-in-Ramadan-Haramain-Umrah-Taxi-Book.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-taxi-pickup-spots-near-masjid-haram",
    title: "Safe & Best Taxi Pickup Points & Spots near Masjid Al Haram",
    excerpt: "Best pickup points near Haram for pilgrims. Read about safe, convenient locations at all gates. Book your Haramain Umrah Taxi ride now at Discounted Price!",
    categories: ["other-services"],
    date: "2026-05-11",
    readTime: "8 min read",
    image: "/images/Safe-Best-Taxi-Pickup-Points-Spots-near-Masjid-Al-Haram-Haramain-Umrah-Taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-book-the-best-umrah-taxi-online-in-makkah-from-the-uk",
    title: "How to Book The Best Umrah Taxi Online in Makkah from the UK?",
    excerpt: "Book your Umrah taxi from the UK to Madinah with ease. Enjoy reliable service, comfortable vehicles, transparent pricing, and smooth transfers with Us!",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "9 min read",
    image: "/images/How-to-Book-The-Best-Umrah-Taxi-Online-in-Makkah-from-the-UK.png",
    author: "M Umar Irfan",
  },
  {
    id: "are-taxi-services-available-at-train-stations-in-saudi-arabia",
    title: "Are Taxi Services Available at Train Stations in Saudi Arabia?",
    excerpt: "Find out if taxis are available at Saudi train stations. Discover easy booking options for Makkah and Madinah hotel transfers with trusted Umrah taxi service.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "8 min read",
    image: "/images/Are-Taxi-Services-Available-at-Train-Stations-in-Saudi-Arabia.png",
    author: "M Umar Irfan",
  },
  {
    id: "jeddah-airport-parking-fees-hajj-north-terminal-1",
    title: "Jeddah Airport Parking Fees: Hajj, North & Terminal 1",
    excerpt: "Complete guide by Haramain Umrah Taxi to Jeddah Airport parking charges at Terminal 1, Hajj & North terminals. Long-term & VIP options. Plan your budget now.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Jeddah-Airport-Parking-Charges-Hajj-North-Terminal-1.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-perform-hajj-badal-for-a-deceased-dead-person",
    title: "How to Perform Hajj Badal for a Deceased & Dead Person?",
    excerpt: "Learn how to perform Hajj Badal for deceased loved ones. Complete step-by-step guide by Haramain Umrah Taxi with rituals & requirements. Book Now.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/How-to-Perform-Hajj-Badal-for-a-Deceased-Dead-Person-.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-perform-umrah-badal-for-a-deceased-dead-person",
    title: "How to Perform Umrah Badal for a Deceased & Dead Person?",
    excerpt: "Discover how to perform Umrah Badal for a deceased person with proper intention and rituals. Trust Haramain Umrah Taxi for reliable Umrah Badal services.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "10 min read",
    image: "/images/How-to-Perform-Umrah-Badal-for-a-Deceased-Dead-Person.png",
    author: "M Umar Irfan",
  },
  {
    id: "wadi-hanifa-garden-park-riyadh-a-complete-tour-guide",
    title: "Wadi Hanifa Garden & Park, Riyadh: A Complete Tour Guide",
    excerpt: "Explore Wadi Hanifa Garden & Park in Riyadh with our complete tour guide with attractions, tips, and travel help by Haramain Umrah Taxi.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Wadi-Hanifa-Garden-Park-Riyadh-A-Complete-Tour-Guide.png",
    author: "M Umar Irfan",
  },
  {
    id: "14-important-taxi-tips-for-pilgrims-or-travelers-in-ksa",
    title: "14 Important Taxi Tips for Pilgrims or Travelers in KSA",
    excerpt: "Learn 14 taxi tips for pilgrims or travelers in KSA. Trust Haramain Umrah Taxi, we follow every safety guideline to protect our pilgrims and tourists.",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/14-Important-Taxi-Tips-for-Pilgrims-or-Travelers-in-KSA.png",
    author: "M Umar Irfan",
  },
  {
    id: "taxi-fare-from-makkah-to-taif-taif-to-makkah-taif-ziyarat",
    title: "Taxi Fare from Makkah to Taif & Taif to Makkah &Taif Ziyarat",
    excerpt: "Affordable taxi service from Makkah to Taif. Rates from SAR 380. Ziyarat tours included. Book Camry, GMC, Hiace, Coaster & Bus. Available 24/7.",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Taxi-Fare-from-Makkah-to-Taif-Taif-to-Makkah-Taif-Ziyarat.png",
    author: "M Umar Irfan",
  },
  {
    id: "taxi-fare-from-makkah-to-masjid-ayesha-masjid-jarana-mikat",
    title: "Taxi Fare from Makkah to Masjid Ayesha & Masjid Jarana Mikat",
    excerpt: "Get reasonable taxi fares from Makkah to Masjid Ayesha & Masjid Jarana Miqat. Fixed rates, 24/7 service. Book your Umrah transport with Haramain Umrah Taxi.",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Taxi-Fare-from-Makkah-to-Masjid-Ayesha-Masjid-Jarana-Mikat.png",
    author: "M Umar Irfan",
  },
  {
    id: "is-it-safe-to-use-taxi-service-in-makkah-medina-ksa-at-night",
    title: "Is it Safe to Use Taxi Service in Makkah, Medina, KSA at Night?",
    excerpt: "People ask, is it safe to use taxi service in Makkah, Medina, KSA at night? Haramain Umrah Taxi offers secure 24/7 travel with verified drivers & GPS tracking.",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Is-it-Safe-to-Use-Taxi-Service-in-Makkah-Medina-KSA-at-Night.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-women-or-female-friendly-taxi-services-in-saudi-arab",
    title: "Best Women or Female-Friendly Taxi Services in Saudi Arab",
    excerpt: "Traveling as a woman in Saudi Arabia just got safer and more comfortable. Discover the best women or female-friendly taxi services in Saudi Arab. Book HUT!",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/Best-Women-or-Female-Friendly-Taxi-Services-in-Saudi-Arab.png",
    author: "M Umar Irfan",
  },
  {
    id: "makkah-train-station-to-hotel-masjid-al-haram-taxi-fare",
    title: "Makkah Train Station to Hotel & Masjid Al Haram Taxi Fare",
    excerpt: "Find the affordable Makkah Train Station to Hotel & Masjid Al Haram Taxi Fare at HUT. We offer comfortable transfers for pilgrims. Reserve your ride with Us!",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/Makkah-Train-Station-to-Hotel-Masjid-Al-Haram-Taxi-Fare-1.png",
    author: "M Umar Irfan",
  },
  {
    id: "how-to-book-a-taxi-in-saudi-arabia-for-international-visitors",
    title: "How to Book a Taxi in Saudi Arabia for International Visitors? ",
    excerpt: "Learn how to book taxi in Saudi Arabia for international visitors. You can travel comfortably between holy cities and do ziyarats. Book HUT today!",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/How-to-Book-a-Taxi-in-Saudi-Arabia-for-International-Visitors.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-places-in-riyadh",
    title: "13 Best Places to Visit in Riyadh & Things to Do in Riyadh",
    excerpt: "Discover the best places to visit in Riyadh. Read our complete guide to top attractions & things to do in the Saudi capital.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "14 min read",
    image: "/images/13-Best-Places-to-Visit-in-Riyadh-Things-to-Do-in-Riyadh.png",
    author: "M Umar Irfan",
  },
  {
    id: "why-taxi-services-in-ksa-request-visa-and-passport-details",
    title: "Why Taxi Services in KSA Request Visa and Passport Details?",
    excerpt: "Discover why KSA taxi services require visa and passport details for pilgrim safety and compliance. Book secure Haramain Umrah Taxi today.",
    categories: ["taxi-guides"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/Why-Taxi-Services-in-KSA-Request-Visa-and-Passport-Details1.png",
    author: "M Umar Irfan",
  },
  {
    id: "donate-quran-makkah-madinah-haram",
    title: "How to Donate Quran in Makkah, Madinah & Masjid Al Haram?",
    excerpt: "Learn how to donate Quran in Makkah & Madinah properly. Complete guide to Waqaf a Quran in Masjid Al Haram & Masjid Nabawi online with official channels.",
    categories: ["other-services"],
    date: "2026-05-12",
    readTime: "11 min read",
    image: "/images/How-to-Donate-Quran-in-Makkah-Madinah-andMasjid-Al-Haram-.png",
    author: "M Umar Irfan",
  },
  {
    id: "badar-ziyarat-list-best-places-badr",
    title: "Badar Ziyarat List | Places to Visit in Badr | Things to Do",
    excerpt: "Complete Badr Ziyarat list with 15 must-visit places including the battlefield, martyrs' graves, and sacred wells. Explore historical Islamic sites of Badr.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "13 min read",
    image: "/images/Badar-Ziyarat-List-Places-to-Visit-in-Badr-Things-to-Do-768x559.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-places-alula-ziyarat-alula",
    title: "List of Best Places to Visit in AlUla & AlUla Ziyarat Tours",
    excerpt: "Explore the best places to visit in AlUla with guided Ziyarat tours. Ancient tombs, rock formations & sacred sites await in Saudi Arabia.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "15 min read",
    image: "/images/List of Best Places to Visit in AlUla & AlUla Ziyarat Tours.png",
    author: "M Umar Irfan",
  },
  {
    id: "15-best-places-to-visit-in-jeddah-with-family-things-to-do",
    title: "15 Best Places to Visit in Jeddah with Family | Things to Do",
    excerpt: "Discover best places to visit in Jeddah with family. From New Corniche & Jeddah Waterfront Park to theme parks & malls, explore top attractions with our guide.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "15 min read",
    image: "/images/15-Best-Places-to-Visit-in-Jeddah-with-Family-Things-to-Do.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-ziyarat-places-madinah",
    title: "15 Best Places to Visit in Madinah| Tourist & Holy Sites Madina",
    excerpt: "Discover 15 best places to visit in Madinah including Masjid al-Nabawi, Mount Uhud, and sacred Ziyarat sites. Get complete guide with history and tips.",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "15 min read",
    image: "/images/15-Best-Places-to-Visit-in-Madinah.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-places-in-makkah",
    title: "20 Best Places to Visit in Makkah During Umrah | Makkah Ziyarat",
    excerpt: "Discover the 20 best places to visit in Makkah during Umrah. From Jabal al-Nour to Jannat al-Mu'alla, explore sacred Ziyarat sites with our complete guide",
    categories: ["sight-seeings"],
    date: "2026-05-12",
    readTime: "15 min read",
    image: "/images/Best-Places-to-Visit-in-Makkah.png",
    author: "M Umar Irfan",
  },
  {
    id: "taxi-fare-jeddah-airport-to-makkah",
    title: "How Much is the Taxi Fare from Jeddah Airport to Makkah?",
    excerpt: "Find out the taxi fare from Jeddah Airport to Makkah with Us. Fixed prices from SAR 250, airport pickup, and direct routes to Masjid al-Haram. Book today!",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/How-Much-is-the-Taxi-Fare-from-Jeddah-Airport-to-Makkah-1.png",
    author: "M Umar Irfan",
  },
  {
    id: "makkah-to-jeddah-and-jeddah-airport-fare",
    title: "How Much is the Makkah to Jeddah & Jeddah Airport Taxi Fare?",
    excerpt: "Discover the Makkah to Jeddah & Jeddah Airport taxi fare with Haramain Umrah Taxi. Fixed rates from SAR 200, professional drivers, and 24/7 service. Book Now!",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/How-Much-is-the-Makkah-to-Jeddah-Jeddah-Airport-Taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "makkah-to-madinah-taxi-fare-distance",
    title: "What is Makkah to Madinah Taxi Fare and Private Car Price?",
    excerpt: "Find out the taxi fare from Makkah to Madinah with Us. Fixed prices from SAR 400, door-to-door service, and professional drivers. Book today!",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/What-is-Makkah-to-Madinah-Taxi-Fare-and-Private-Car-Price.png",
    author: "M Umar Irfan",
  },
  {
    id: "madinah-to-makkah-taxi-fare-distance",
    title: "What is Madinah to Makkah Taxi Fare or Price and Distance?",
    excerpt: "Discover Madinah to Makkah taxi fare starting at SAR 400. We cover 450km in 4-5 hours with fixed prices and professional drivers. Book your comfortable travel.",
    categories: ["taxi-fares"],
    date: "2026-05-12",
    readTime: "12 min read",
    image: "/images/What-is-Madinah-to-Makkah-Taxi.png",
    author: "M Umar Irfan",
  },
  {
    id: "best-umrah-taxi-online",
    title: "Best Umrah Taxi Online in Makkah, Madinah | Umrah Taxi Service",
    excerpt: "Book the best online Umrah taxi service in Makkah and Madinah. Professional drivers, reliable service, transparent pricing & 24/7 support. Reserve your ride now!",
    categories: ["other-services"],
    date: "2026-05-23",
    readTime: "12 min read",
    image: "/images/best-umrah-taxi-online.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "top-islamic-ziyarat-taif",
    title: "List of 9 Top Islamic Ziyarat & Historical Places in Taif",
    excerpt: "Discover 9 must-visit Islamic Ziyarat sites in Taif. Explore Prophet Muhammad's sacred journey, ancient mosques & blessed valleys. Book your Taif tour now!",
    categories: ["sight-seeings"],
    date: "2026-05-23",
    readTime: "13 min read",
    image: "/images/list-of-9-top-islamic-ziyarat.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "taxi-booking-advance-ksa",
    title: "Benefits of Booking Airport or Umrah Taxi in Advance in KSA",
    excerpt: "Discover the benefits of pre-booking your airport or Umrah taxi in Saudi Arabia. Save money, ensure availability & enjoy peace of mind. Book with Haramain Umrah Taxi now!",
    categories: ["other-services"],
    date: "2026-05-23",
    readTime: "11 min read",
    image: "/images/benefit-of-booking-airpot.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "best-time-umrah",
    title: "Best Time to Perform Umrah | Least Crowded Time for Umrah",
    excerpt: "Discover the best time to perform Umrah. Learn about least crowded months, weather conditions & budget-friendly seasons. Plan your perfect Umrah journey!",
    categories: ["other-services"],
    date: "2026-05-23",
    readTime: "12 min read",
    image: "/images/best-time-to-perform-umrah.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "umrah-taxi-south-african",
    title: "Book Online Umrah Taxi for South African Pilgrims at Cheap Fares",
    excerpt: "Book affordable online Umrah taxi services for South African pilgrims. Safe, comfortable transfers from Jeddah to Makkah & Madinah. Reserve your ride now!",
    categories: ["other-services"],
    date: "2026-05-23",
    readTime: "10 min read",
    image: "/images/book-online-umrah-taxi-for-south-african.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "umrah-taxi-usa",
    title: "Private Umrah Taxi Services Online from the USA Book at Discount",
    excerpt: "Book private Umrah taxi services online from USA at discounted prices. Comfortable, reliable airport transfers to Makkah & Madinah. Reserve your ride now!",
    categories: ["other-services"],
    date: "2026-05-23",
    readTime: "10 min read",
    image: "/images/private-umrah-taxi-service-from-usa.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "identify-tent-mina",
    title: "How Can You Find or Identify Your Tents in Mina during Hajj?",
    excerpt: "Complete guide to finding your tent in Mina during Hajj. Learn Maktab system, landmarks & tips to avoid getting lost among thousands of tents. Expert advice inside!",
    categories: ["other-services"],
    date: "2026-05-23",
    readTime: "11 min read",
    image: "/images/how-to identify-you-tent-in-mina.jpeg",
    author: "M Umar Irfan",
  },
  {
    id: "private-car-for-makkah-from-jeddah-airport",
    title: "How to Get a Private Car for Makkah from Jeddah Airport?",
    excerpt: "Do you want to get the best discounted private car for Makkah from Jeddah Airport? WhatsApp or Call Us, we provide 24/7 Jeddah airport to Makkah private cars",
    categories: ["taxi-guides"],
    date: "2026-06-02",
    readTime: "8 min read",
    image: "/images/How to Get a Private Car for Makkah from Jeddah Airport.jpeg",
    author: "M Umar Irfan",
  },
];

export const POSTS_PER_PAGE = 9;

const months = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

export function formatDate(dateStr: string) {
  const date = new Date(dateStr);
  const day = date.getDate();
  const month = months[date.getMonth()];
  const year = date.getFullYear();
  return `${month} ${day}, ${year}`;
}

export const sortedBlogPosts = [...blogPosts].sort(
  (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
);
